#
# Makefile for the ROSY configuration drivers.
#

obj-$(CONFIG_FINGERPRINT_ROSY)	+= fingerprint/
obj-$(CONFIG_TOUCHSCREEN_ROSY)	+= touchscreen/
obj-$(CONFIG_LED_ROSY)			+= led/
obj-$(CONFIG_SOC_ROSY)			+= soc/
obj-$(CONFIG_PSTORE_ROSY)		+= pstore/
